// Auto-generated by OpenLane
module top(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input aclk,
  input aresetn,
  input[15:0] s_axis_tdata,
  input s_axis_tvalid,
  output s_axis_tready,
  output[31:0] m_axis_tdata,
  output m_axis_tvalid,
  input m_axis_tready
);
endmodule
